### ISSUE TITLE
コミットの[]内の操作 on readme.md

### ISSUE THREAD

**Issue by lv7777** [kurosuke18/inmu_ANALects#1]
> modify : ファイルの中身を変更（追加、又は削除）

modifyはｼｭｰ...正って意味なので追加はupdateとかのほうが良いと思うゾ＾

いいリポジトリしてんねぇ！通りでねえ！

**Comment by kurosuke18** [comment]
あっ、そっかぁ（納得）
確かにupdateのほうが分かりやすいですねクォレハ...
じゃけんREADMEを変更しましょうね～

**Comment by kurosuke18** [comment]
修正終わり！閉廷！
